server:
	error:
		include-message: always 
		include-binding-errors: always 
spring:
	datasource:
	password: 
	url: jdbc:postgresql://localhost:5432/prism
	username:
jpa:
	hibernate:
		ddl-auto: create-drop
	properties:
		properties:
			hibernate:
				format_sql: true
		show-sql: true 